import Head from "next/head";
import { Project } from "@/components/views/Project";

const ProjectPage = () => {
  return (
    <>
      <Head>
        <title>Big Screen Show - Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Project />
    </>
  );
};

export default ProjectPage;
