import Head from "next/head";
import { Project } from "@/components/views/Project";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";

export const getServerSideProps = (async (context) => {
  const res = await fetch("https://dev9.paradigma-digital.ru/projects/");
  const data = await res.json();

  const project = data.filter((project: any) => {
    return (
      project.NAME.split(" ").join("-").toLowerCase() === context.query.slug
    );
  });

  return { props: { project } };
}) satisfies GetServerSideProps<{
  project: any;
}>;

const ProjectPage = ({
  project,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Big Screen Show - {project[0] && project[0].NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Project project={project[0]} />
    </>
  );
};

export default ProjectPage;
