import Head from "next/head";
import { Product } from "@/components/views/Product";

const ProductPage = () => {
  return (
    <>
      <Head>
        <title>Big Screen Show - Product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Product />
    </>
  );
};

export default ProductPage;
