import Head from "next/head";
import { Product } from "@/components/views/Product";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";

export const getServerSideProps = (async (context) => {
  const res = await fetch("https://dev9.paradigma-digital.ru/equipment/");
  const data = await res.json();
  const product = Object.values(data).map((product: any) => {
    //@ts-ignore
    let item = [];
    const filteredProduct = Object.values(product.CHILD).map((child) => {
      //@ts-ignore
      return Object.values(child.ITM);
    });
    filteredProduct.forEach((obj) => {
      const filter = obj.filter((obj2) => {
        return (
          //@ts-ignore
          obj2.CONTENT["Заголовок"].split(" ").join("-").toLowerCase() ===
          context.query.slug
        );
      });
      item.push(filter[0]);
    });
    //@ts-ignore
    return item[0];
  });

  const result = product[0];
  if (!result) {
    return {
      notFound: true,
    };
  }
  //@ts-ignore
  return { props: { result } };
}) satisfies GetServerSideProps<{
  result: any;
}>;

const ProductPage = ({
  result,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Big Screen Show - {result.CONTENT["Заголовок"]}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Product product={result} />
    </>
  );
};

export default ProductPage;
