import Head from "next/head";

import { Error } from "@/components/views/Error";

const CatalogPage = () => {
  return (
    <>
      <Head>
        <title>Big Screen Show - 404</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Error />
    </>
  );
};

export default CatalogPage;
