import Head from "next/head";

import { Catalog } from "@/components/views/Catalog";

const CatalogPage = () => {
  return (
    <>
      <Head>
        <title>Big Screen Show - Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Catalog />
    </>
  );
};

export default CatalogPage;
