import Head from "next/head";

import { Catalog } from "@/components/views/Catalog";
import { GetStaticProps, InferGetStaticPropsType } from "next";

export const getStaticProps = (async (context) => {
  const res = await fetch("https://adm.bss-tv.com/equipment/");
  const products = await res.json();

  return { props: { products } };
}) satisfies GetStaticProps<{
  products: any;
}>;

const CatalogPage = ({
  products,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <>
      <Head>
        <title>Big Screen Show - Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Catalog products={Object.values(products)} />
    </>
  );
};

export default CatalogPage;
