import Head from "next/head";

import { Contacts } from "@/components/views/Contacts";

const ContactsPage = () => {
  return (
    <>
      <Head>
        <title>Big Screen Show - Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Contacts />
    </>
  );
};

export default ContactsPage;
