import Head from "next/head";
import { VideoStudio } from "@/components/views/VideoStudio";
export async function getServerSideProps() {
  return { props: {} };
}
const VideoStudioPage = () => {
  return (
    <>
      <Head>
        <title>Big Screen Show - Video Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VideoStudio />
    </>
  );
};

export default VideoStudioPage;
