import Head from "next/head";
import { VideoProjection } from "@/components/views/VideoProjection";

const VideoStudioPage = () => {
  return (
    <>
      <Head>
        <title>Big Screen Show - Video Projection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VideoProjection />
    </>
  );
};

export default VideoStudioPage;
