import Head from "next/head";
import { Projects } from "@/components/views/Projects";
import { GetStaticProps, InferGetStaticPropsType } from "next";

export const getStaticProps = (async (context) => {
  const res = await fetch("https://dev9.paradigma-digital.ru/projects/");
  const projects = await res.json();

  return { props: { projects } };
}) satisfies GetStaticProps<{
  projects: any;
}>;

const ProjectsPage = ({
  projects,
}: InferGetStaticPropsType<typeof getStaticProps>) => {

  return (
    <>
      <Head>
        <title>Big Screen Show - Проекты</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Projects projects={projects} />
    </>
  );
};

export default ProjectsPage;
